[package]
name = "factorio_mod_control"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "fmc"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinyjson = "2.5.1"
